package main

type Dictionary struct {
	engWord  string
	persWord string
}

// func makeDictionary() []Dictionary {
func makeDictionary() map[string]string {
	result := map[string]string{
		"aeroadrome":       "فرودگاه",
		"airport":          "فرودگاه",
		"atm":              "خودپرداز",
		"bank":             "بانک",
		"bus_station":      "ایستگاه اتوبوس",
		"cafe":             "کافه",
		"car_rental":       "اجاره اتومبیل",
		"car_wash":         "کارواش",
		"club":             "باشگاه",
		"college":          "دانشکده",
		"courthouse":       "دادگاه",
		"dentist":          "دندانپزشک",
		"doctors":          "شاختمان پزشکان",
		"driving_school":   "آموزشگاه رانندگی",
		"embassy":          "سفارت",
		"fast_food":        "فست فود",
		"ferry_terminal":   "کشتیرانی",
		"fire_station":     "ایستگاه آتشنشانی",
		"health_centre":    "مرکز بهداشت",
		"hotel":            "هتل",
		"kindergarten":     "مهد کودک",
		"library":          "کتابخانه",
		"marketplace":      "بازار",
		"nursery":          "شیر خوارگاه",
		"office":           "دفتر",
		"park":             "پارک",
		"parking":          "پارکینگ",
		"pharmacy":         "داروخانه",
		"police":           "پلیس",
		"post_office":      "دفتر پست",
		"prison":           "زندان",
		"restaurant":       "رستوران",
		"retirement_home":  "خانه بازنشستگان",
		"school":           "مدرسه",
		"shelter":          "پناهگاه",
		"shop":             "فروشگاه",
		"studio":           "استدیو",
		"taxi":             "تاکسی",
		"theatre":          "تئاتر",
		"toilets":          "سرویس بهداشتی",
		"townhall":         "شهرداری",
		"university":       "دانشگاه",
		"veterinary":       "دامپزشکی",
		"youth_centre":     "مرکز جوانان",
		"clinic":           "کلینیک",
		"country":          "کشور",
		"square":           "میدان",
		"city":             "استان",
		"town":             "شهر",
		"village":          "روستا",
		"farm":             "مزرعه",
		"house":            "خانه",
		"island":           "جزیره",
		"suburb":           "حومه شهر",
		"locality":         "محل",
		"sea":              "دریا",
		"neighbourhood":    "محله",
		"municipality":     "شهرداری",
		"bakery":           "نانوایی",
		"butcher":          "قصاب",
		"kiosk":            "کیوسک",
		"supermarket":      "سوپر مارکت",
		"mall":             "مرکز خرید",
		"computer":         "کامپیوتر",
		"بلبرینگ و ابزار":  "بلبرینگ و ابزار",
		"department_store": "مجتمع تجاری",
		"insurance":        "بیمه",
		"canal":            "کانال",
		"river":            "رودخانه",
		"waterfall":        "آبشار",
		"motel":            "متل",
		"museum":           "موزه",
		"zoo":              "باغ وحش",
		"administrative":   "بخش",
		"apartments":       "آپارتمان",
		"block":            "بخش",
		"bunker":           "پناهگاه",
		"chapel":           "نمازخانه",
		"church":           "کلیسا",
		"commercial":       "تجاری",
		"dormitory":        "خوابگاه",
		"entrance":         "ورودی",
		"faculty":          "دانشکده",
		"flats":            "طبقات",
		"garage":           "گاراژ",
		"hospital":         "بیمارستان",
		"public":           "عمومی",
		"residential":      "مسکونی",
		"retail":           "خرده فروشی",
		"stadium":          "ورزشگاه",
		"store":            "فروشگاه",
		"terrace":          "تراس",
		"tower":            "برج",
		"train_station":    "ایستگاه اتوبوس",
		"station":          "ایستگاه",
		"bridleway":        "پل ",
		"bus_stop":         "ایستگاه اتوبوس",
		"gate":             "گیت",
		"path":             "مسیر",
		"road":             "جاده",
		"primary":          "خیابان اصلی",
		"secondary":        "خیابان فرعی",
		"trunk":            "بزرگراه",
		"cemetery":         "قبرستان",
		"farmland":         "زمین کشاورزی",
		"forest":           "جنگل",
		"grass":            "علف",
		"industrial":       "صنعتی",
		"yes":              "yes",
		"garden":           "باغ",
		"battlefield":      "میدان جنگ",
		"building":         "ساختمان",
		"castle":           "قلعه",
		"icon":             "icon",
		"mine":             "معدن",
	}

	return result
}
